brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = false
fn_args_layout = "Vertical"
force_multiline_blocks = true
format_strings = true
match_block_trailing_comma = true
max_width = 60
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
unstable_features = true

# Imports
imports_granularity="Crate"
reorder_imports = true
reorder_modules = true
imports_indent = "Block"
imports_layout = "Vertical"
