@startuml intra
skinparam componentStyle uml1

package "gm" {
    package "persistence" as per {
        interface "Facade" as perf{
            + PersistenceEventHandler get_persistence_event_handler()
            + LoadEventPublisher get_load_event_publisher()
        }

        struct "SimpleLoadEventPublisher" as perslep {}
        interface "LoadEventPublisher" as perlep {}
        interface "LoadEventSubscriber" as perles {}

        struct "SimpleFacade" as persf {
            - PersistedValueEventHandler persistence_event_handler
            - LoadEventPublisher load_event_publisher
        }

        struct "SimpleFacadeFactory" as persff {
            + Facade create_facade()
        }

        interface "PersistenceEventHandler" as perpeh {}
        struct "UnqlitePersistenceEventHandler" as persupeh {
            - UnQLite unq_document
        }

        package "event" as pere {
            interface "..." as pereellipse {}
        }
    }
}

package "roopes" as r {
    package "publisher_subscriber" as rps{
        interface "Publisher" as rpsp {}
        interface "Subscriber" as rpss {}
    }
}

package "unqlite" as unq {
    struct "UnQLite" as unqunq
}

perlep --> perles
perlep --|> rpsp

perslep ..|> perlep

persff --> perf
persff --> persf
persff --> persupeh
persff --> perslep

persf ..|> perf
persf --* perpeh
persf --* perlep

perf --> perlep
perf --> perpeh

persupeh ..|> perpeh
persupeh --* unqunq

perles --|> perpeh
perles --|> rpss

perpeh --|> pereellipse

@enduml