@startuml
skinparam componentStyle uml1
skinparam defaultFontName DejaVu Serif
skinparam linetype ortho

node "Host System" {
    [GlyphMosaic] as gm
    [File System] as fs
    [Window Manager] as wm
    [Browser] as br
}


gm -u-> fs
gm -u-> wm
gm -u-> br

@enduml