@startuml context
skinparam componentStyle uml1
skinparam defaultFontName DejaVu Serif

person "User" as usr

agent "GlyphMosaic" as gm

package Filesystem as fs {
  file "Source Image" as si
  file "Source Text" as st
  file "GM Document" as gd
  file "Output Image" as oi
}

usr --> gm

gm --> si
gm --> gd
gm --> oi
gm --> st

usr --> si
usr --> st
usr --> oi

@enduml