@startuml data_flow
skinparam componentStyle uml1
skinparam defaultFontName DejaVu Serif
skinparam linetype ortho

start

: user changes parameter [ui];

repeat :parameter changed;

switch (Notify PropertyChange [document])
case (line parameter)
    : Update Line Model [line];
case (source parameter)
    : Update Source [source];
case (core parameters)
    : Write to store [persistence];

endswitch


stop

@enduml