@startuml top_level_modules
skinparam ranksep 25
skinparam componentStyle uml1
skinparam defaultFontName DejaVu Serif

component "region" as reg
component "line" as line
component "point" as pts
component "letter" as let

line -u-> reg : 1
pts -u-> line : 2
pts -u-> reg : 3
let -u-> pts : 4

@enduml