@startuml
skinparam componentStyle uml1
skinparam defaultFontName DejaVu Serif
skinparam linetype ortho

start

split
    :Load Source Image;
split again
    :Load Source Text;
split again
    :Add Regions;
    :Modify Region Glyph Parameters;
end split

:Render Output;

stop

@enduml