@startuml workflow
skinparam componentStyle uml1
skinparam defaultFontName DejaVu Serif
skinparam linetype ortho

start

split
    :Load Document;
split again
    :Create Document;
end split

repeat
    :Render Output;
    :Modify Parameter;
repeatwhile ()

stop

@enduml