@startuml inter
skinparam componentStyle uml1

package "gm" as gm {
    component document as doc
}

package "roopes"  as roopes {
    component "publisher_subscriber" as rps
    component "visitor" as rpv
}


doc -u-> rps
doc -u-> rpv


@enduml