@startuml intra
skinparam componentStyle uml1

package "gm::ui" as ui {
    interface "Facade" as uif{
    }

    struct "SimpleFacadeFactory" as uisff {
        + Facade create_facade()
    }
    struct "SimpleFacade" as uisf {
    }
}

' package "roopes"  as roopes {
'     package "patterns::publisher_subscriber" as rps {
'         interface "MutablePublisher" as rmpsp
'         interface "Subscriber" as rpss

'         package "vec_publisher" as rpsvp {
'             struct "VecPublisher" as rpsvpvp
'         }
'     }
' }


uisf ..|> uif
uisff --> uisf
uisff --> uif

@enduml