@startuml bitmap
skinparam componentStyle uml1

package "gm::bitmap" {
    interface "BitMap" as bm{
        + usize get_h_px()
        + usize get_v_px()
    }

    struct "SimpleBitMap" as bms {
        - ColorImage mat
    }

    interface "Cache" as bmc{
        + HeapPool get_pool()
    }

    struct "SimpleCache" as bmsc{
    }

    interface "Facade" as bmf{
        + BitMap get_bitmap(usize h_px, usize v_px)
    }

    struct "SimpleFacade" as bmsf{
        - Cache cache
    }

    struct "SimpleFacadeFactory" as bmsff{
        + Facade create_facade()
    }

    struct "SimpleBitMapBuilder" as bmsbmb{
    }
}


package "roopes"{
    package "primitives::emitter" {
        interface "Emitter" as ree {}

        package "lambda" {
            struct "Lambda" as rel {}
        }
    }

    package "patterns::heap_pool" {
        interface "HeapPool" as rhphp {}
        struct "RefCellBox" as rhphrcb{}
    }
}

package eframe::egui {
    struct "ColorImage" as eeci {}
}

bmc --> bm
bmc --|> rhphp

bmf --> bm

bms ..|> bm
bms --> eeci

bmsbmb --> bms

bmsc --* rhphp
bmsc ..|> bmc

bmsf --* bmc
bmsf ..|> bmf

bmsff --> bmsbmb
bmsff --> rhphrcb
bmsff --> bmsc
bmsff --> bmsf
bmsff --> rel
bmsff --> bmf

rhphrcb --* ree
rhphrcb ..|> rhphp

rel ..|> ree

@enduml