@startuml
skinparam componentStyle uml1

package "gm::document" as doc {
    interface "Facade" as docf{
        + void InitializeDocument()
        + void SaveDocument()
        + void LoadDocument(location: Path)
        + void AttachDocumentPropertyChangeSubscriber(sub: DocumentPropertyChangeSubscriber)
        + DocumentPropertyChangeSubscriber DocumentPropertyChangeSubscriber()
    }

    enum "DocumentProperty" as docp {
        Font(TODO)
        SourceImage(BitMap)
        SourceText(String)
        OutputScale(f32)
        RegionProperty(TODO, RegionProperty)
    }

    enum "RegionProperty" as docrp {
        PathDilationMask(BitMap)
        GlyphPathKernel(BitMap)
        GutterLineHeight(f32)
        LineHeight(usize)
        GlyphKerning(f32)
        GlyphMinimumSize(f32)
        GlyphMaximumSize(f32)
        DensitySampleSize(f32)
        GlyphRotationSampleSize(f32)
        PathGenerationScale(f32)
    }

    interface "PropertyChangePublisher" as docpcp
    interface "PropertyChangeSubscriber" as docpcs
    interface "PropertyChangeVisitor" as docpcv

    struct "SimpleFacadeFactory" as docsff {
        + Facade create_facade()
    }
    struct "SimpleFacade" as docsf {
        - property_change_publisher: "PropertyChangePublisher"
    }
    struct "DocumentBitmapSerializer" as docbmpser

    package "FileSystem" as docfs {
        struct "PropertyChangeVisitor" as docfspcv
        struct "PropertyChangePublisher" as docfspcp
    }

    package "LocalStorage" as docls {
        struct "DocumentPropertyChangeVisitor" as doclspcv
        struct "DocumentPropertyChangePublisher" as doclspcp
    }
}

package "roopes" {
    package "patterns::publisher_subscriber" as rps {
        interface "MutablePublisher" as rmp
        interface "Subscriber" as rs

        package "vec_publisher" {
            struct "VecPublisher" as rvp
        }
    }

    package "derive::visitor" as rvmod{
        interface "Visitor" as rv
    }
}

package "web_sys" as ws { 
    struct "Storage" as wss
}

package "sqlite" as sql {
    struct "Connection" as sqlc
}

docf --> docpcs

docsf ..|> docf
docsf --* docpcp

docsff --> docsf
docsff --> docf

docpcs --|> rs

docfspcp --> docbmpser

docfspcp ..|> docpcp
docfspcv ..|> docpcv
docfspcv --> sqlc
docfspcp --* rvp
docfspcp -d[hidden]- docfspcv

doclspcv --> wss
doclspcv ..|> docpcv
doclspcp --> docbmpser
doclspcp ..|> docpcp
doclspcp --* rvp
doclspcp -d[hidden]- doclspcv

docpcp --|> rmp

docpcv --|> rv
docpcv --> docp
docpcv --> docrp

docsff --> doclspcp
docsff --> doclspcv
docsff --> docfspcp
docsff --> docfspcv

@enduml