@startuml
component GUI {
    component "Preview Area"
    component "Parameters Area"
}

component CLI

component Library {
    component "Backend Manager"
    component "Document"
    component "Sources"
    component "Region"
    component "Lines"
    component "Points"
    component "Glyphs"
    component "Export"
}

@enduml