name: Build Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Nix Store Cache
        uses: actions/cache@v3
        with:
          key: nix-store
          path: /nix/store

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: shell.nix

      - name: Setup Cargo Cache
        uses: actions/cache@v3
        with:
          key: cargo-store
          path: target

      - name: Init
        run: just reinit-workspace

      - name: Build
        run: just build-documentation
