name: Build Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            keep-outputs = true

      - name: Nix Cache
        uses: nix-community/cache-nix-action@v3
        with:
          key: cache-${{ matrix.os }}-${{ hashFiles('**/*.nix') }}
          restore-keys: |
            cache-${{ matrix.os }}-
          gc-linux: true
          gc-max-store-size-linux: 1000000000

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: shell.nix

      - name: Build
        run: just build-documentation

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "documentation/Specification.pdf"
          prerelease: true
