name: Make Documentation

on:
  push:
    branches: ["main", "ci"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache Nix Store
        uses: actions/cache@v3
        with:
          path: /nix/store
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: shell.nix
      - name: Init
        run: just reinit-workspace
      - name: Build
        run: just build-documentation
