name: Make Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Plantuml
      run: sudo apt-get install -y plantuml
    - name: Install Latex
      run: sudo apt-get install -y latexmk
    - name: Make Documentation
      run: make documentation
